name: selenium

on:
  push:
    branches:
      - selenium

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    services:
      firefox:
        image: selenium/standalone-firefox:4.0
        ports: ["4444:4444"]
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'
      - run: npm install -g

      - name: run Selenium
        run: |
          /home/runner/work/FINDCov19TrackerData/FINDCov19TrackerData/node_modules/.bin/selenium-side-runner -c "browserName=firefox" --server http://localhost:4444/wd/hub -w 2 manual/scrap_tests_data.side.yml
